### PR TITLE
Uptime Percentage

### PR DESCRIPTION
**Pull request by DagBAndersen**

### CODE REVIEW

**Comment by gustavclausen** [comment]
What about a simple "X %" instead of a graph? 🙂

**Comment by DagBAndersen** [comment]
Why not see it over time - then we have a history of when it was down and up

**Comment by gustavclausen** [comment]
Uhm, I don’t know how beneficial it is to see a percentage envolve over time 🤔
But okay

**Comment by DagBAndersen** [comment]
The whole thing feels useless 😭

**Comment by DagBAndersen** [comment]
I guess it is beneficial to see how long the server was down...

**Pull request merged**
